version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vidventure-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  pgdata: