import '~/services/firebase';

import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ModalProvider } from '~/providers/ModalProvider';
import { UserProvider } from '~/providers/UserProvider';
import Header from '~/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ModalProvider>
            <div className="flex flex-col">
              <Header />
              {children}
            </div>
          </ModalProvider>
        </UserProvider>
      </body>
    </html>
  );
}
