import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import AuthenticatedUserCheck from '~/components/AuthenticatedUserCheck';
import Header from '~/components/Header';
import MaxWidthWrapper from '~/components/MaxWidthWrapper';
import { cn } from '~/lib/utils';
import { QueryProvider } from '~/providers/QueryProvider';
import { UserProvider } from '~/providers/UserProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          'relative h-full font-sans antialiased overflow-hidden',
          inter.className
        )}
        style={{
          backgroundImage: `url(/background.png)`,
          backgroundSize: 'cover',
          backgroundRepeat: 'no-repeat',
        }}
      >
        <QueryProvider>
          <UserProvider>
            <div className="flex flex-col">
              <Header />
              <AuthenticatedUserCheck>
                <MaxWidthWrapper>{children}</MaxWidthWrapper>
              </AuthenticatedUserCheck>
            </div>
          </UserProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
