name: Test and Build
'on':
  push:
    branches:
      - main
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Or any version you prefer

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests and build
      - name: Build
        run: npm test && npm run build
        env:
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
